"""Add Phase 7 curriculum and personalization models

Revision ID: d2259ac9663b
Revises: 001
Create Date: 2026-03-26 03:16:17.105804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.base import GUID


# revision identifiers, used by Alembic.
revision: str = 'd2259ac9663b'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'chat_session_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('curriculum_progress', 'id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('curriculum_progress', 'student_profile_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('hardware_configs', 'id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('hardware_configs', 'student_profile_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_ingestion_logs_created_at'), table_name='ingestion_logs')
    op.drop_index(op.f('ix_reindex_jobs_created_at'), table_name='reindex_jobs')
    op.add_column('student_profiles', sa.Column('skill_level', sa.String(length=20), nullable=False))
    op.alter_column('student_profiles', 'id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('student_profiles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=GUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('student_profiles', 'user_id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('student_profiles', 'id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('student_profiles', 'skill_level')
    op.create_index(op.f('ix_reindex_jobs_created_at'), 'reindex_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ingestion_logs_created_at'), 'ingestion_logs', ['created_at'], unique=False)
    op.alter_column('hardware_configs', 'student_profile_id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('hardware_configs', 'id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('curriculum_progress', 'student_profile_id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('curriculum_progress', 'id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'user_id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'chat_session_id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=GUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
